version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: ./app
    container_name: python_app
    command: bash -c "python main.py && tail -f /dev/null"
    volumes:
      - ./app:/app
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: user_password
      DB_NAME: mydb
    depends_on:
      - mysql
